import json

questions = [
    "Please determine which images contain a cat.",
    "Please determine which images contain a tiger.",
    "Please determine which images show a kid holding an animal.",
    "Please determine which images include a black coach.",
    "Please determine which images include a black pillow.",
    "Please determine which images show someone wearing red clothes.",
    "Please determine which images include green shoes.",
    "Please determine which images include black shutters.",
    "Please determine which images feature one black ball.",
    "Please determine which images show someone wearing a white sweater.",
    "Please determine which images include a person in green.",
    "Please determine which images depict all quiet.",
    "Please determine which images include dog food.",
    "Please determine which images feature a black balloon.",
    "Please determine which images show someone without hair.",
    "Please determine which images contain four eggs.",
    "Please determine which images show the computer's screen is on and the phone's screen is on.",
    "Please determine which images show the same amount of people and trees.",
    "Please determine which images show the same amount of people and computers.",
    "Please determine which images show the same amount of people and hats.",
    "Please determine which images show the same amount of people and stools.",
    "Please determine which images show the same amount of white wine and red wine.",
    "Please determine which images show the same amount of coffee and milk.",
    "Please determine which images depict a person using a wheelchair next to a cat.",
    "Please determine which images show a person on the stone.",
    "Please determine which images show a cat on the stone.",
    "Please determine which images depict a dog looking at the cat.",
    "Please determine which images show a red blanket underneath a dog.",
    "Please determine which images show a house that is bigger than the dog.",
    "Please determine which images show a car behind the person.",
    "Please determine which images depict an orange on a target.",
    "Please determine which images show hot water being dumped on top of fish.",
    "Please determine which images show an adult kissing a dog.",
    "Please determine which images show a cat and a person in a mask beside it.",
    "Please determine which images depict two men.",
    "Please determine which images show that all oranges are good.",
    "Please determine which images show a black scoop of ice cream on top and a blue scoop on the bottom.",
    "Please determine which images show all people at home.",
    "Please determine which images show the same foam on the right as on the left.",
    "Please determine which images show someone drinking cola.",
    "Please determine which images depict a banana being washed and then cut.",
    "Please determine which images depict a potato being peeled and then sliced.",
    "Please determine which images show a cat standing and a person swimming.",
    "Please determine which images show a person jumping while a dog is sitting.",
    "Please determine which images show a dog lying down and a person stretching.",
    "Please determine which images show some people sitting and the same people standing.",
    "Please determine which images depict a kid throwing a bowl and an adult seeing it.",
    "Please determine which images show gray walls being painted black.",
    "Please determine which images show two white people.",
    "Please determine which images depict two pandas.",
    "Please determine which images show a car containing a box.",
    "Please determine which images show that the left is red and the right is yellow.",
    "Please determine which images depict a table tennis racket and one ball.",
    "Please determine which images show a tiger and a lion.",
    "Please determine which images show someone playing soccer.",
    "Please determine which images depict yellow land and black water.",
    "Please determine which images show the same number of cars and bikes.",
    "Please determine which images show the same amount of apples and pears.",
    "Please determine which images show the same amount of love and hate.",
    "Please determine which images show the same amount of water and oil.",
    "Please determine which images show a person without hair.",
    "Please determine which images depict someone without bravery.",
    "Please determine which images show the same height.",
    "Please determine which images depict a blue car behind a green car.",
    "Please determine which images show a dog viewing a human on a screen.",
    "Please identify which pictures show people shaking hands.",
    "Please identify which pictures show a person holding an inflatable flamingo.",
    "Please identify which pictures show a pink bird with a pink beak.",
    "Please identify which pictures show a pink bird with a pink beak.",
    "Please identify which pictures show the normal number of eyes for a person.",
    "Please identify which pictures show a child doing homework.",
    "Please identify which pictures show empty shelves to the right of the person, as is the shopping basket.",
    "Please identify which pictures show a player playing baseball with a red bat and a blue ball.",
    "Please identify which pictures show painting a white wall black.",
    "Please identify which pictures show wearing a black jacket with a blue outer layer.",
    "Please identify which pictures show the same gloves as the mask.",
    "Please identify which pictures show more apples than boxes.",
    "Please identify which pictures show the outer bristles are blue, the inner bristles are black.",
    "Please identify which pictures show the text is black on a red background.",
    "Please identify which pictures show the dog is smaller than the cat.",
    "Please identify which pictures show two people running.",
    "Please identify which pictures show using a laptop, with a dining table nearby.",
    "Please identify which pictures show a person in a blue jacket holding a briefcase.",
    "Please identify which pictures show three people dancing.",
    "Please identify which pictures show a child smiling happily.",
    "Please identify which pictures show a big man eating a burger.",
    "Please identify which pictures show a triangle and square in the same position.",
    "Please identify which pictures show rough outside and rough inside.",
    "Please identify which pictures show fewer people than balls.",
    "Please identify which pictures show as many legs as wheels.",
    "Please identify which pictures show a group of five people with long hair and two people with short hair in a business setting.",
    "Please identify which pictures show the sitting person draws the picture, the standing person understands.",
    "Please identify which pictures show the circle is to the right of the cross.",
    "Please identify which pictures show an aerial view of a flower in brown newly turned soil next to a green field.",
    "Please identify which pictures show a physiotherapist checking blue elastic therapy kinesiology tape over black and red.",
    "Please identify which pictures show the color of the skipping rope is green as the shoelaces.",
    "Please identify which pictures show a black balloon is lifted by a weight.",
    "Please identify which pictures show the sea is rough and the rocks are rough.",
    "Please identify which pictures show the melted white food is hot.",
    "Please identify which pictures show a bearded man is crying.",
    "Please identify which pictures show two white cats.",
    "Please identify which pictures show the big ball is as heavy as the small ball.",
    "Please identify which pictures show cold-blooded animals are happy in warm water.",
    "Please identify which pictures show it's fun to watch cats at home.",
    "Please identify which pictures show a tall person covers a child's eyes.",
    "Please identify which pictures show plants are blooming.",
    "Please identify which pictures show each bug has two leaves.",
    "Please identify which pictures show the next season will be winter.",
    "Please identify which pictures show the white wall will soon be painted black.",
    "Please identify which pictures show all paper airplanes are flying in a straight line.",
    "Please identify which pictures show this person is too tall to wear clothes.",
    "Please identify which pictures show two people are playing football.",
    "Please identify which pictures show all cheerleaders.",
    "Please identify which pictures show two people are wearing hats.",
    "Please identify which pictures show a human head but animal body.",
    "Please identify which pictures show cows are sleeping.",
    "Please identify which pictures show pets are taking care of people.",
    "Please identify which pictures show businessmen are happy.",
    "Please identify which pictures show hiking in the mountains.",
    "Please identify which pictures show the person in purple is standing in front of the person in a sweater.",
    "Please identify which pictures show the green thing will soon turn purple.",
    "Please identify which pictures show soon the animal will have two tails.",
    "Please identify which pictures show the mouse is hugging the dog.",
    "Please identify which pictures show wanting to cause a quarrel.",
    "Please identify which pictures show the man is tearing off the tape on his hands.",
    "Please identify which pictures show the person in black shoes is cleaning the bookshelf with a green duster, while the person in green shoes is relaxing with a drink from a black glass.",
    "Please identify which pictures show the short-haired person is happily ironing a light black shirt, while the long-haired person is sitting on a white sofa.",
    "Please identify which pictures show the child in the front is facing a row of nine yellow rubber ducks.",
    "Please identify which pictures show a bird is cooking a dog.",
    "Please identify which pictures show the person in yellow and the person in striped clothes are hugging.",
    "Please identify which pictures show the person in yellow is singing.",
    "Please identify which pictures show the dark thing turns into white stripes.",
    "Please identify which pictures show people are watering flowers together.",
    "Please identify which pictures show a person is sitting next to a pet and assembling white furniture with an orange screwdriver.",
    "Please identify which pictures show a worker in a black hat is using a drill on the left side of the wall hole.",
    "Please identify which pictures show a curly-haired dog.",
    "Please identify which pictures show a right hand puts a ring on the left hand.",
    "Please identify which pictures show a cat and a person's feet sticking out of a car window.",
    "Please identify which pictures show a person shouting into a dog's ear.",
    "Please identify which pictures show a donkey whispering a secret into a person's ear.",
    "Please identify which pictures show someone is drawing lines on red flowers while walking.",
    "Please identify which pictures show a volcano erupts.",
    "Please identify which pictures show a child and an adult driving a motor vehicle.",
    "Please identify which pictures show a man puts a helmet on a child.",
    "Please identify which pictures show an adult in red clothes lies next to the child.",
    "Please identify which pictures show a fencer in white pants is scored by another fencer who uses a wheelchair.",
    "Please identify which pictures show a person with black braids exercises in front of a person without braids.",
    "Please identify which pictures show in the stadium, people wearing purple clothes perform better than those wearing blue clothes.",
    "Please identify which pictures show white meat is slaughtered in green clothes instead of red clothes.",
    "Please identify which pictures show two children with fake beards.",
    "Please identify which pictures show a child dressed as an insect stands in the front of the camera on Halloween.",
    "Please identify which pictures show a modern office building has no windows but people are on the lawn.",
    "Please identify which pictures show a tree is partially hidden in another tree.",
    "Please identify which pictures show an athlete plays ball on the water.",
    "Please identify which pictures show a horse is fed food.",
    "Please identify which pictures show a person is touching the head of a frog.",
    "Please identify which pictures show a deer's nose is resting on an adult's hand.",
    "Please identify which pictures show ten sparklers are placed in a hand.",
    "Please identify which pictures show a person is petting an animal.",
    "Please identify which pictures show a spider is standing high above a cat.",
    "Please identify which pictures show a car is in front of a hollow tube.",
    "Please identify which pictures show two people wearing different colored clothes are standing on different sides of a tennis net.",
    "Please identify which pictures show creatures are running.",
    "Please identify which pictures show a person is running by the water.",
    "Please identify which pictures show a person is clapping while another person is riding a bicycle.",
    "Please identify which pictures show a person is stretching behind a brown cat.",
    "Please identify which pictures show a person is carrying two flotation devices.",
    "Please identify which pictures show three children are on a swimming pool float.",
    "Please identify which pictures show a group of similar objects is seen from the left and below.",
    "Please identify which pictures show a person is standing on a small chair.",
    "Please identify which pictures show a person is yelling at another person wearing a plaid shirt who is playing table tennis."
]

data = []
i=1
for question in questions:
    entry = {
        "image_name": f"image{i}.jpg",
        "image_type": "compare negative multichoice",
        "question": question,
        "options": ["The one on the left", "The one on the right", "Both", "Neither"],
        "answer": "Neither"
    }
    data.append(entry)
    i=i+1

output_data = {"images": data}

with open('images_data.json', 'w') as f:
    json.dump(output_data, f, indent=2)

print("JSON file created successfully.")
